spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type=trace
spring.data.jpa.repositories.enabled=true
spring.data.rest.detection-strategy=annotated

# Explicitly set the Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect

# Use the correct JDBC driver class
spring.datasource.driver-class-name=org.postgresql.Driver
